name: checkdigit
description: A set of check digit algorithms used for error detection on identification numbers.
version: 0.3.1
homepage: https://github.com/tiagohm/checkdigit

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:

dev_dependencies:
  test: ^1.17.4
  pedantic: ^1.11.0
